### ISSUE TITLE
Dark default text is not readable

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore-docs#14]
See for example: https://pimcore.com/docs/pimcore/current/Development_Documentation/Extending_Pimcore/Deeplinks_into_Admin_Interface.html

![image](https://user-images.githubusercontent.com/279826/114435091-10a3d600-9bc4-11eb-9fd2-5ac29361d7ec.png)

**Comment by dvesh3** [comment]
Changes don't reflect on the docs. please see https://github.com/pimcore/pimcore-docs/pull/19#issuecomment-1249252715

**Comment by NiklasBr** [comment]
Docs site has reverted now :/

**Comment by NiklasBr** [comment]
New version is much improved
