### ISSUE TITLE
[Bug]: Issue with the link for bundles in the documentation 

### ISSUE THREAD

**Issue by aryaantony92** [pimcore/pimcore-docs#28]
### Expected behavior

In the documentation for bundles, (for eg: https://pimcore.com/docs/advanced-object-search/current/), when we click on the "Edit on Github" link, it will be redirected to the correct documentation link in the github.

### Actual behavior

In the documentation for bundles, (for eg: https://pimcore.com/docs/advanced-object-search/current/), when we click on the "Edit on Github" link, it will be redirected to the documentation link in the github (like https://github.com/pimcore/advanced-object-search/edit/4.x/doc/README.md). But, in the github, there is no readme file inside the doc folder for the bundles,  

### Steps to reproduce

Check the link  "Edit on Github" in the documentation of a bundle. 

Related to #27

**Comment by brusch** [comment]
Obsolete.
