### ISSUE TITLE
[Bug]: Academy Pimcore Developer Senior - documentation hyperlink to 404

### ISSUE THREAD

**Issue by bformelalm** [pimcore/pimcore-docs#30]
### Expected behavior

In the "Working with Objects Advanced" course of the "Pimcore Developer Senior" certificate, the "Relation Datatypes" chapter, after clicking on the hyperlink in the "Further Information" section you are redirected to the appropriate subpage of the Pimcore documentation; in this case: "Reverse Many-To-Many Object Relation".

### Actual behavior

In the "Working with Objects Advanced" course of the "Pimcore Developer Senior" certificate, the "Relation Datatypes" chapter, after clicking on the "Reverse Many-To-Many Object Relation" link in the "Further Information" section you are redirected to the 404 subpage.

### Steps to reproduce

1. Go to: https://pimcore.com/academy/course/Working-with-Objects-Advanced~100627/chapter-100635.
2. Scroll to the "Further Information" section at the bottom of the page.
3. Click on the hyperlink [Reverse Many-To-Many Object Relation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Reverse_Many_To_Many_Object_Relation_Type.html).

**Comment by brusch** [comment]
Thanks for reporting - link is fixed.
