### ISSUE TITLE
[Bug]: Statistics Explorer Links Broken

### ISSUE THREAD

**Issue by julkue** [pimcore/pimcore-docs#31]
### Expected behavior

Clicking on links of the documentation of the Statistics Explorer are working.

### Actual behavior

The repo doesn't seem to exist anymore or is private.

### Steps to reproduce

Click on the link "DummyTracker" on this page: https://pimcore.com/docs/statistics-explorer/2.0/Tracking_Events.html

**Comment by brusch** [comment]
Link is working for me now, seems that this got fixed already 😊

**Comment by julkue** [comment]
@brusch No, it's still not. You must click on the link "DummyTracker" on the referenced documentation. The link will be https://github.com/pimcore/statistics-explorer/blob/master/src/StatisticsTracker/Elasticsearch/DummyTracker.php which is still 404. At least for me. Might be, that you are contributor on this repo and you can see it, but I can't.

**Comment by brusch** [comment]
@julmot the statistics-explorer is an enterprise bundle, you need access to it 😉
