### ISSUE TITLE
[Bug]: New docs site missing changelogs

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore-docs#32]
### Expected behavior

< 10.6 changeslog should be avaialble

### Actual behavior

Can only find 10..6 and 11 changes

### Steps to reproduce

Visit: https://pimcore.com/docs/platform/Platform_Version/Release_Notes/ and search for it

**Comment by brusch** [comment]
See https://github.com/pimcore/pimcore/issues/15217
