### ISSUE TITLE
[Bug]: Academy pages are jumping on autoSliding

### ISSUE THREAD

**Issue by kaurov** [pimcore/pimcore-docs#37]
### Expected behavior

Content has a stable vertical position, so you can read it

### Actual behavior

Academy pages like https://pimcore.com/academy/course/Pimcore-X-Highlights~150684/chapter-152477
have multiple images galleries with images of different height.
After some time those galleries start to automatically slide/scroll images from left to right.
That very moment all content below the gallery with images of different height is jumping vertically.
Just try to read content in semi-transparent slides of 3+ gallery.

### Steps to reproduce

open https://pimcore.com/academy/course/Pimcore-X-Highlights~150684/chapter-152477

scroll down to 4th gallery 'Other Changes' and wait until all upper galleries will start autoscrolling.

OS: MacOs
Browser: Chrome Version 116.0.5845.140 (Official Build) (x86_64)

**Comment by NiklasBr** [comment]
Same problem as I have since a while ago.

https://github.com/pimcore/pimcore/discussions/9528

**Comment by kaurov** [comment]
This is already solved
